spring:
  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST}/${AUTH_DB_NAME}?sslmode=require
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${FRONTEND_URL}/auth/callback/google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${FRONTEND_URL}/auth/callback/github
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${FRONTEND_URL}
