spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
          github:
            scope:
              - read:user
              - user:email

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Move jwt config outside of spring block
jwt:
  secret: your_jwt_secret_key_for_development
  expiration: 86400000

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.security: DEBUG

cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  allow-credentials: true
