name: CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/ci.yml'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: code_racer_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Backend Tests
        working-directory: ./backend
        run: |
          go mod download
          go test -v ./...
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: code_racer_test
          DB_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test_secret
